## Server properties
server:
  port: 8096

## Database configuration
spring:
  application:
    apiBasePath: fhir
  datasource:
    ##url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    ##username: ${DB_USER}
    ##password: ${DB_PASS}
    url: jdbc:postgresql://localhost:5432/challenge_uphill
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop